import { useEffect, useState, type FormEvent } from 'react'
import { getStudentResponses, updateStudent } from '../../../lib/api'
import type { Student, StudentResponse } from '../dashboard/types'
import Button from '../../../shared/components/ui/Button'

function educationLevelFromStudentCode(studentCode:string){const levels:Record<string,string>={B:'ปริญญาตรี',M:'ปริญญาโท',D:'ปริญญาเอก'};return levels[studentCode.trim().charAt(0).toUpperCase()]??'ไม่ระบุ'}

function ParticipantDetailDrawer({student,onClose,onSaved}:{student:Student|null;onClose:()=>void;onSaved:(student:Student)=>void}){
 const [draft,setDraft]=useState(student);const [responses,setResponses]=useState<StudentResponse[]>([]);const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 useEffect(()=>{if(student)getStudentResponses(student.id).then(setResponses).catch(e=>setError(e instanceof Error?e.message:'โหลดประวัติไม่ได้'))},[student])
 if(!draft)return null
 const save=async(e:FormEvent)=>{e.preventDefault();if(!/^[BMD]\d{7}$/.test(draft.studentCode.toUpperCase())){setError('รหัสนักศึกษาต้องขึ้นต้น B, M หรือ D ตามด้วยตัวเลข 7 หลัก');return}setSaving(true);setError('');try{const updated=await updateStudent(draft.id,{studentCode:draft.studentCode.toUpperCase(),firstName:draft.firstName,lastName:draft.lastName,email:draft.email,faculty:draft.faculty,major:draft.major,educationLevel:educationLevelFromStudentCode(draft.studentCode),phone:draft.phone,pdpaConsentedAt:draft.pdpaConsentedAt});onSaved(updated);setDraft(updated)}catch(x){setError(x instanceof Error?x.message:'บันทึกไม่ได้')}finally{setSaving(false)}}
 const set=(key:keyof Student,value:string|null)=>setDraft({...draft,[key]:value})
 return <div className="student-drawer-backdrop" onMouseDown={onClose}><aside className="student-drawer" role="dialog" aria-modal="true" aria-labelledby="student-detail-title" onMouseDown={e=>e.stopPropagation()}><header><div><small>{draft.studentCode}</small><h2 id="student-detail-title">ข้อมูลนักศึกษา</h2></div><Button onClick={onClose}>×</Button></header><form onSubmit={save}><div className="student-form-grid"><label>รหัสนักศึกษา<input required value={draft.studentCode} onChange={e=>set('studentCode',e.target.value)}/></label><label>อีเมล<input required type="email" value={draft.email} onChange={e=>set('email',e.target.value)}/></label><label>ชื่อ<input required value={draft.firstName} onChange={e=>set('firstName',e.target.value)}/></label><label>นามสกุล<input required value={draft.lastName} onChange={e=>set('lastName',e.target.value)}/></label><label>คณะ<input value={draft.faculty??''} onChange={e=>set('faculty',e.target.value||null)}/></label><label>สาขา<input value={draft.major??''} onChange={e=>set('major',e.target.value||null)}/></label><label>ระดับการศึกษา<input value={draft.educationLevel??''} onChange={e=>set('educationLevel',e.target.value||null)}/></label><label>เบอร์โทร<input value={draft.phone??''} onChange={e=>set('phone',e.target.value||null)}/></label><label>ยินยอม PDPA เมื่อ<input type="datetime-local" value={draft.pdpaConsentedAt?.slice(0,16)??''} onChange={e=>set('pdpaConsentedAt',e.target.value?new Date(e.target.value).toISOString():null)}/></label></div>{error&&<p role="alert">{error}</p>}<Button disabled={saving} type="submit">{saving?'กำลังบันทึก...':'บันทึกข้อมูล'}</Button></form><section className="student-response-history"><h3>กิจกรรมและประวัติการตอบ</h3><p>แสดงเฉพาะสถานะการส่ง ไม่เปิดเผยคำตอบรายข้อ</p>{responses.length===0?<div className="empty-state">ยังไม่มีประวัติการตอบ</div>:<ul>{responses.map(r=><li key={r.id}><div><strong>{r.activityName}</strong><small>{r.activityCode??'—'}</small></div><span className={`response-phase response-phase--${r.phase}`}>{r.phase.toUpperCase()}</span><time>{new Date(r.submittedAt).toLocaleString('th-TH')}</time></li>)}</ul>}</section></aside></div>
}
export default ParticipantDetailDrawer
